<a href="https://colab.research.google.com/github/JuanGutierrezP/Juan_Guti-rrez-Joseph_Reyes/blob/main/Tarea_lineal_Joseph_Juan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
#Punto 2
import numpy as np

# sistema
A = np.array([[3., -1., -1.],
              [-1., 3., 1.],
              [2., 1., 4.]])
b = np.array([1., 3., 7.])
def gauss_seidel(A, b, x0=None, tol=1e-10, max_iter=1000):
    n = len(b)
    if x0 is None:
        x = np.zeros(n)
    else:
        x = x0.copy()
    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            sum_ = 0
            for j in range(n):
                if j != i:
                    sum_ += A[i, j] * x[j]
            x[i] = (b[i] - sum_) / A[i, i]
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            print(f"Convergencia hecha en {k+1} iteraciones.")
            return x
    print("No se alcanzó la convergencia después del número máximo de iteraciones posibles")
    return x

x0 = np.zeros(len(b))
x_sol = gauss_seidel(A, b, x0)
print("Solución aproximada:")
print(x_sol)

# Verificar la solución
residual = np.dot(A, x_sol) - b
print("Residual:")
print(residual)


Convergencia hecha en 18 iteraciones.
Solución aproximada:
[1. 1. 1.]
Residual:
[ 4.78932449e-11 -3.27688987e-11  0.00000000e+00]


In [38]:
#Punto 3
import numpy as np
class LinearSolver:
    def __init__(self, A, b):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.n = len(b)
    def jacobi(self, x0=None, tol=1e-10, max_iterations=1000):
        A = self.A
        b = self.b
        n = self.n
        x = np.zeros(n) if x0 is None else x0
        D = np.diag(np.diag(A))
        R = A - D
        iterations = 0
        for i in range(max_iterations):
            x_new = (b - np.dot(R, x)) / np.diag(A)
            iterations += 1

            if np.linalg.norm(x_new - x, ord=np.inf) < tol:
                print(f"Método de Jacobi convergió en {iterations} iteraciones.")
                return x_new
            x = x_new
        print(f"Método de Jacobi no convergió en {max_iterations} iteraciones.")
        return x
    def gauss_seidel(self, x0=None, tol=1e-10, max_iterations=1000):
        A = self.A
        b = self.b
        n = self.n
        x = np.zeros(n) if x0 is None else x0
        iterations = 0
        for k in range(max_iterations):
            x_new = np.copy(x)
            for i in range(n):
                # s1 y s2 para sumar los productos anteriores
                s1 = np.dot(A[i, :i], x_new[:i])
                s2 = np.dot(A[i, i+1:], x[i+1:])
                x_new[i] = (b[i] - s1 - s2) / A[i, i]
            iterations += 1
            # Verificar la convergencia
            if np.linalg.norm(x_new - x, ord=np.inf) < tol:
                print(f"Método de Gauss-Seidel convergió en {iterations} iteraciones.")
                return x_new
            x = x_new
        print(f"Método de Gauss-Seidel no convergió en {max_iterations} iteraciones.")
        return x

A = [[10, 2, -1],[-3, -6, 2],[1, 1, 5]]
b = [27, -61.5, -21.5]
solver = LinearSolver(A, b)
# método de Jacobi
x_jacobi = solver.jacobi()
print("Solución por Jacobi:", x_jacobi)
# Gauss-Seidel
x_gauss_seidel = solver.gauss_seidel()
print("Solución por Gauss-Seidel:", x_gauss_seidel)


Método de Jacobi convergió en 22 iteraciones.
Solución por Jacobi: [ 0.5  8.  -6. ]
Método de Gauss-Seidel convergió en 13 iteraciones.
Solución por Gauss-Seidel: [ 0.5  8.  -6. ]


In [39]:
#Punto 4

def matriz_multi(A, B):
    # Obtener las dimensiones de las matrices A y B
    filas_A = len(A)
    columnas_A = len(A[0])
    filas_B = len(B)
    columnas_B = len(B[0])

    if columnas_A != filas_B:
        raise ValueError("No se pueden multiplicar las matrices: son dimensiones incompatibles.")

    #matriz de ceros
    res = [[0 for _ in range(columnas_B)] for _ in range(filas_A)]

    # multiplicación de matrices
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                res[i][j] += A[i][k] * B[k][j]

    return res

# Definir las matrices A y B
A = [
    [1, 0, 0],
    [5, 1, 0],
    [-2, 3, 1]]

B = [
    [4, -2, 1],
    [0, 3, 7],
    [0, 0, 2]]

# Calcular el producto AB
AB = matriz_multi(A, B)
# Imprimir el resultado
print("El producto de las matrices A y B es :")
for fila in AB:
    print(fila)


El producto de las matrices A y B es :
[4, -2, 1]
[20, -7, 12]
[-8, 13, 21]


In [15]:
#Punto 5
#PDF

In [16]:
#Punto 6
#PDF


In [40]:
#Punto 8
import numpy as np
def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Construcción de U
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += L[i][j] * U[j][k]
            U[i][k] = A[i][k] - sum

        # Construcción de L
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal de L es 1
            else:
                sum = 0
                for j in range(i):
                    sum += L[k][j] * U[j][i]
                L[k][i] = (A[k][i] - sum) / U[i][i]
    return L, U
# Definir la matriz A
A = np.array([
    [4, -2, 1],
    [20, -7, 12],
    [-8, 13, 17]
], dtype=float)

# Realizar la descomposición LU
L, U = lu_decomposition(A)

# Mostrar los resultados
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

# Verificar que A = L * U
A_reconstructed = np.dot(L, U)
print("\n(A reconstruida):")
print(A_reconstructed)


Matriz L:
[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]

Matriz U:
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]

(A reconstruida):
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 17.]]


In [41]:
#Punto 10
import numpy as np

#a)
def jacobi_eigenvalue(A, tol=1e-10, max_iterations=100):
    n = A.shape[0]
    A = A.copy()
    V = np.eye(n)
    iterations = 0

    for _ in range(max_iterations):
        # Encontrar el elemento fuera de la diagonal más grande en valor absoluto
        off_diag = np.abs(A - np.diag(np.diagonal(A)))
        i, j = np.unravel_index(np.argmax(off_diag), A.shape)
        if A[i, j] == 0 or np.abs(A[i, j]) < tol:
            break

        # Calcular el ángulo theta
        if A[i, i] == A[j, j]:
            theta = np.pi / 4
        else:
            theta = 0.5 * np.arctan2(2 * A[i, j], A[i, i] - A[j, j])

        # Construir la matriz de rotación
        R = np.eye(n)
        R[i, i] = np.cos(theta)
        R[j, j] = np.cos(theta)
        R[i, j] = -np.sin(theta)
        R[j, i] = np.sin(theta)

        # Actualizar A y V
        A = R.T @ A @ R
        V = V @ R
        iterations += 1

    # Los valores propios son los elementos diagonales de A
    eigenvalues = np.diagonal(A)
    # Los vectores propios son las columnas de V
    Propiovectors = V

    return eigenvalues, Propiovectors, iterations

# Matriz A proporcionada
A = np.array([
    [4, 1, 1],
    [1, 3, 2],
    [1, 2, 5]
], dtype=float)

# Ejecutar el método de Jacobi
eigenvalues, Propiovectors, iterations = jacobi_eigenvalue(A)

# Ordenar los valores y vectores propios
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
Propiovectors = Propiovectors[:, idx]

# Mostrar los resultados
print(f"Número de iteraciones: {iterations}\n")
print("Valores propios obtenidos por el método de Jacobi:")
print(eigenvalues)
print("\nVectores propios correspondientes:")
print(Propiovectors)

eigvals_numpy, eigvecs_numpy = np.linalg.eig(A)
# Ordenar los valores propios de NumPy
idx_numpy = np.argsort(eigvals_numpy)[::-1]
eigvals_numpy = eigvals_numpy[idx_numpy]
eigvecs_numpy = eigvecs_numpy[:, idx_numpy]

print("\nValores propios de numpy:")
print(eigvals_numpy)
print("\nVectores propios correspondientes de numpy:")
print(eigvecs_numpy)


Número de iteraciones: 8

Valores propios obtenidos por el método de Jacobi:
[6.89510652 3.39729507 1.70759841]

Vectores propios correspondientes:
[[ 0.43170413  0.88573564 -0.17059871]
 [ 0.49725362 -0.07589338  0.86427949]
 [ 0.75257583 -0.45794385 -0.47319874]]

Valores propios de numpy:
[6.89510652 3.39729507 1.70759841]

Vectores propios correspondientes de numpy:
[[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]


In [30]:
#Punto 12
import numpy as np

def newton_raphson_system(f, J, x0, tol=1e-8, max_iter=100):
    x = x0.copy()
    for i in range(max_iter):
        Fx = f(x)
        Jx = J(x)

        delta = np.linalg.solve(Jx, -Fx)
        x = x + delta
        if np.linalg.norm(delta, ord=2) < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x
    print("No se alcanzó la convergencia")
    return x
def F1(x):
    x1, x2 = x
    return np.log(x1**2 + x2**2) - np.sin(x1 * x2) - np.log(2) - np.log(np.pi)

def F2(x):
    x1, x2 = x
    return np.exp(x1 - x2) + np.cos(x1 * x2)
def F(x):
    return np.array([F1(x), F2(x)])

# Definir el Jacobiano corregido
def J(x):
    x1, x2 = x
    denom = x1**2 + x2**2
    J11 = (2 * x1) / denom - x2 * np.cos(x1 * x2)
    J12 = (2 * x2) / denom - x1 * np.cos(x1 * x2)
    J21 = np.exp(x1 - x2) - x2 * np.sin(x1 * x2)
    J22 = -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)
    return np.array([[J11, J12], [J21, J22]])
# Valor inicial
x0 = np.array([2.0, 2.0])

solution_nr = newton_raphson_system(F, J, x0)
print("Solución (Newton-Raphson):", solution_nr)
def gradient_descent_system(f, J, x0, alpha=0.01, tol=1e-8, max_iter=1000):
    x = x0.copy()
    for i in range(max_iter):
        Fx = f(x)
        grad_phi = J(x).T @ Fx
        x_new = x - alpha * grad_phi
        if np.linalg.norm(x_new - x, ord=2) < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x_new
        x = x_new
    print("No se alcanzó la convergencia.")
    return x

# método de descenso del gradiente
solution_gd = gradient_descent_system(F, J, x0)
print("Solución (Descenso del Gradiente):", solution_gd)

def newton_raphson_system(f, J, x0, tol=1e-8, max_iter=100):
    x = x0.copy()
    for i in range(max_iter):
        Fx = f(x)
        Jx = J(x)
        try:
            delta = np.linalg.solve(Jx, -Fx)
        except np.linalg.LinAlgError:
            print("Error: Jacobiano singular.")
            return x
        x_new = x + delta
        if np.linalg.norm(delta, ord=2) < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x_new
        x = x_new
    print("No se alcanzó la convergencia.")
    return x

def newton_raphson_system(f, J, x0, tol=1e-8, max_iter=100):
    x = x0.copy()
    for i in range(max_iter):
        Fx = f(x)
        Jx = J(x)
        # Resolver Jx * delta = -Fx
        try:
            delta = np.linalg.solve(Jx, -Fx)
        except np.linalg.LinAlgError:
            print("Error: Jacobiano singular.")
            return x
        x = x + delta
        if np.linalg.norm(delta, ord=2) < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x
    print("No se alcanzó la convergencia.")
    return x

# funciones corregidas
def F_system2(x):
    x1, x2, x3 = x
    f1 = 6 * x1 - 2 * np.cos(x2 * x3) - 1
    f2 = 9 * x2 + np.sqrt(x1**2 + np.sin(x3) + 1.06) + 0.9
    f3 = 60 * x3 + 3 * np.exp(-x1 * x2) + 10 * np.pi - 3
    return np.array([f1, f2, f3])

# Definir el Jacobiano corregido
def J_system2(x):
    x1, x2, x3 = x
    J = np.zeros((3, 3))
    # Derivadas parciales para f1
    J[0, 0] = 6
    J[0, 1] = 2 * x3 * np.sin(x2 * x3)
    J[0, 2] = 2 * x2 * np.sin(x2 * x3)
    # Derivadas parciales para f2
    denom = 2 * np.sqrt(x1**2 + np.sin(x3) + 1.06)
    if denom != 0:
        J[1, 0] = x1 / denom
        J[1, 2] = (np.cos(x3)) / denom
    else:
        J[1, 0] = 0
        J[1, 2] = 0
    J[1, 1] = 9
    # Derivadas parciales para f3
    J[2, 0] = -3 * x2 * np.exp(-x1 * x2)
    J[2, 1] = -3 * x1 * np.exp(-x1 * x2)
    J[2, 2] = 60
    return J

x0_system2 = np.array([0.0, 0.0, 0.0])
#  Newton-Raphson
solution_nr2 = newton_raphson_system(F_system2, J_system2, x0_system2)
print("Solución (Newton-Raphson):", solution_nr2)

def gradient_descent_system(f, J, x0, alpha=1e-4, tol=1e-8, max_iter=10000):
    x = x0.copy()
    for i in range(max_iter):
        Fx = f(x)
        grad_phi = J(x).T @ Fx
        x_new = x - alpha * grad_phi
        if np.linalg.norm(x_new - x, ord=2) < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x_new
        x = x_new
    print("No se alcanzó la convergencia.")
    return x
solution_gd2 = gradient_descent_system(F_system2, J_system2, x0_system2)
print("Solución (Descenso del Gradiente):", solution_gd2)

Convergencia alcanzada en 6 iteraciones.
Solución (Newton-Raphson): [1.77245385 1.77245385]
Convergencia alcanzada en 544 iteraciones.
Solución (Descenso del Gradiente): [1.77245351 1.7724542 ]
Convergencia alcanzada en 5 iteraciones.
Solución (Newton-Raphson): [ 0.49814468 -0.1996059  -0.52882598]
Convergencia alcanzada en 3359 iteraciones.
Solución (Descenso del Gradiente): [ 0.49814193 -0.19960563 -0.52882594]


In [42]:
#Punto 13

import numpy as np

def jacobian_order4(F, x, h=1e-5):
    n = len(x)
    Fx = F(x)
    m = len(Fx)
    J = np.zeros((m, n))
    h_vec = np.zeros_like(x)

    for i in range(n):
        h_vec[i] = h
        f_plus_2h = F(x + 2*h_vec)
        f_plus_h = F(x + h_vec)
        f_minus_h = F(x - h_vec)
        f_minus_2h = F(x - 2*h_vec)
        J[:, i] = (-f_plus_2h + 8*f_plus_h - 8*f_minus_h + f_minus_2h) / (12*h)
        h_vec[i] = 0

    return J

def jacobian_order2(F, x, h=1e-5):
    n = len(x)
    Fx = F(x)
    m = len(Fx)
    J = np.zeros((m, n))
    h_vec = np.zeros_like(x)

    for i in range(n):
        h_vec[i] = h
        f_plus_h = F(x + h_vec)
        f_minus_h = F(x - h_vec)
        J[:, i] = (f_plus_h - f_minus_h) / (2*h)
        h_vec[i] = 0

    return J

def F_system(x):
    x1, x2, x3 = x
    f1 = 6*x1 - 2*np.cos(x2 * x3) - 1
    f2 = 9*x2 + np.sqrt(x1**2 + np.sin(x3) + 1.06) + 0.9
    f3 = 60*x3 + 3*np.exp(-x1 * x2) + 10*np.pi - 3
    return np.array([f1, f2, f3])


x_point = np.array([0.5, 0.5, 0.5])

h = 0.01

# Calcular Jacobiano con(h^4)
J_order4 = jacobian_order4(F_system, x_point, h)
print("Jacobiano con operador de orden O(h^4):")
print(J_order4)

# Calcular Jacobiano con (h^2)
J_order2 = jacobian_order2(F_system, x_point, h)
print("\nJacobiano con operador de orden O(h^2):")
print(J_order2)

#h = 0.0001 para igualar precisiones
h_new = 0.0001
J_order2_new = jacobian_order2(F_system, x_point, h_new)
print("\nJacobiano con operador de orden O(h^2) y h=0.0001:")
print(J_order2_new)


Jacobiano con operador de orden O(h^4):
[[ 6.          0.24740396  0.24740396]
 [ 0.37377753  9.          0.32802064]
 [-1.16820117 -1.16820117 60.        ]]

Jacobiano con operador de orden O(h^2):
[[ 6.          0.24740293  0.24740293]
 [ 0.37376854  9.          0.32801836]
 [-1.16820604 -1.16820604 60.        ]]

Jacobiano con operador de orden O(h^2) y h=0.0001:
[[ 6.          0.24740396  0.24740396]
 [ 0.37377753  9.          0.32802064]
 [-1.16820118 -1.16820118 60.        ]]


In [43]:
#Punto 14
import sympy as sp

# Definir símbolos
x, y, z = sp.symbols('x y z')

# Generadores del grupo SO(3)
J_x = sp.Matrix([
    [0,  0,  0],
    [0,  0, -1],
    [0,  1,  0]
])

J_y = sp.Matrix([
    [0,  0,  1],
    [0,  0,  0],
    [-1, 0,  0]
])

J_z = sp.Matrix([
    [0, -1,  0],
    [1,  0,  0],
    [0,  0,  0]
])

# símbolo de Levi-Civita
def levi_civita(i, j, k):
    if (i, j, k) in [(1, 2, 3), (2, 3, 1), (3, 1, 2)]:
        return 1
    elif (i, j, k) in [(3, 2, 1), (2, 1, 3), (1, 3, 2)]:
        return -1
    else:
        return 0

# generadores
generators = [J_x, J_y, J_z]
generador_cu = ['J_x', 'J_y', 'J_z']

def print_commutator(name1, name2, result):
    print(f"\nConmutador [{name1}, {name2}]:")
    sp.pprint(result)

#  conmutadores
for i in range(3):
    for j in range(3):
        if i < j:
            Ji = generators[i]
            Jj = generators[j]
            comm = Ji * Jj - Jj * Ji
            # Encontrar k tal que (i, j, k) es una permutación de (0, 1, 2)
            k = 3 - i - j
            epsi = levi_civita(i+1, j+1, k+1)
            expected = epsi * generators[k]
            print_commutator(generador_cu[i], generador_cu[j], comm)
            print(f"¿[{generador_cu[i]}, {generador_cu[j]}] = ε{i+1}{j+1}{k+1} * {generador_cu[k]}?")
            sp.pprint(comm.equals(expected))



Conmutador [J_x, J_y]:
⎡0  -1  0⎤
⎢        ⎥
⎢1  0   0⎥
⎢        ⎥
⎣0  0   0⎦
¿[J_x, J_y] = ε123 * J_z?
True

Conmutador [J_x, J_z]:
⎡0  0  -1⎤
⎢        ⎥
⎢0  0  0 ⎥
⎢        ⎥
⎣1  0  0 ⎦
¿[J_x, J_z] = ε132 * J_y?
True

Conmutador [J_y, J_z]:
⎡0  0  0 ⎤
⎢        ⎥
⎢0  0  -1⎥
⎢        ⎥
⎣0  1  0 ⎦
¿[J_y, J_z] = ε231 * J_x?
True
